### ISSUE TITLE
No `get_vertex_color()` for assimp::Mesh

### ISSUE THREAD

**Issue by SiebenCorgie** [Eljay/assimp-rs#13]
Hi,

I am currently using this really useful crate to import my models. However, i recently wanted to integrate vertex colors but can't find any good way to get the vertex color per index/vertex. Am I missing something or is this not yet implemented?

thanks in advance!

-siebencorgie

**Comment by Eljay** [comment]
Hi, `get_vertex_color` and `vertex_color_iter` have been added to `Mesh` in version 0.2.1.
