### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by OTL** [Eljay/assimp-rs#16]
I'm using assim-rs for [my project](https://github.com/OTL/urdf-viz), and it works fine on Linux.
Thank you for great project!

But it has a problem when i build my project on OSX(Sierra), and attached the console output.
[error.txt](https://github.com/Eljay/assimp-rs/files/1384505/error.txt)

Do you have any advice?

- I can build assimp-sys and assimp-rs its self on OSX.
- the error occurs when i build urdf-viz on OSX.

**Comment by OTL** [comment]
I'm debugging this issue.

I tried to run examples/render.rs on MacOS, but I couldn't.
The log is below.
[error_render_master.txt](https://github.com/Eljay/assimp-rs/files/1404622/error_render_master.txt)

This seems that the issue of core-graphics, so i tried to update glium.
I'll send PL soon, could you check it?
(I have no environments in which glium and assimp-rs works (My laptop is MacOS, and in VMs, glium does not work)

Then I got the similar error as  I attached in previous comment.
This is the error message.
[error_render.txt](https://github.com/Eljay/assimp-rs/files/1404624/error_render.txt)

It seems that it is related to libc++, but I don't know what to do.

**Comment by OTL** [comment]
Finally I found the solution.

https://github.com/Eljay/assimp-sys/pull/17

**Comment by repi** [comment]
Just tested the latest and I had no problems to build for OS X. Time to resolve this issue?

**Comment by FredrikNoren** [comment]
Cool, thanks for testing @repi
